### ISSUE TITLE
Colors of some titles are too dark

### ISSUE THREAD

**Issue by roiholtzman** [dracula/wolfram-notebooks#3]
I have an issue with the colors of the titles. See for instance the photo here - the color of some of the titles is too dark. Is it something specific to my setup? Or something has changed in Mathematica 12.2?

<img width="1260" alt="Screen Shot 2021-12-16 at 9 39 02" src="https://user-images.githubusercontent.com/7188052/146328384-ec88064e-9e48-49ef-b367-5b64d3cf9b28.png">

**Comment by jldohmann** [comment]
Hi @roiholtzman no, there's nothing wrong with your setup. They're just cell styles that I don't use much

If you end up opening a PR for a change in color for these cell styles, here's the dracula color palette: https://draculatheme.com/contribute#color-palette

**Comment by roiholtzman** [comment]
@jldohmann  I didn't understand where I can change them. Can you point me to the right direction?

**Comment by jldohmann** [comment]
@roiholtzman check out the file `Dracula.nb` which is the stylesheet that contains all the rules for which headings get certain colors. This is the file that would be edited to either change or include the cells you're interested in. 

E.g., for Section cells:

```
Cell[
  StyleData["Section"], 
  FontColor -> RGBColor[
  0.8274509803921568, 0.8274509803921568, 0.8274509803921568
]]
```

**Comment by roiholtzman** [comment]
@jldohmann  I tried to edit this file, but I do not succeed. Is the file "locked" somehow?
(Sorry for my beginner's questions, I just do not see how to edit this file).

**Comment by jldohmann** [comment]
@roiholtzman it's alright 🙂 The easiest way to change a style is to follow the workflow ["Edit a Style in a Notebook's Stylesheet"](https://reference.wolfram.com/language/workflow/EditAStyleInANotebooksStylesheet.html) which walks you thru the steps of editing stylesheets. 

However, you will get more customization if you convert the cell in question to its [expression form](https://reference.wolfram.com/language/ref/menuitem/ShowExpression.html), and change any corresponding options to what you would like. For certain style defintions, like [`StyleData[Notebook]`](https://github.com/dracula/wolfram-notebooks/blob/51b0591509d4f2968f73fb100c38b26e3490f62c/Dracula.nb#L35), this is especially useful because there are many fine tuned options within.

**Comment by roiholtzman** [comment]
@jldohmann thank you so much! I was able to do it now:)
I put my custom stylesheet in the appropriate folder (which is opened via `SystemOpen[FileNameJoin[{$UserBaseDirectory,"SystemFiles","FrontEnd","StyleSheets"}]]` as written in the installation instructions).
To make it my default stylesheet, I ran `SetOptions[$FrontEnd, DefaultStyleDefinitions->"DraculaCustom.nb"]`, and everything is perfect. 
Thanks!
